name: Prettier

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   prettier:
      runs-on: ubuntu-latest
      name: Prettier
      steps:
         - name: Check out code
           uses: actions/checkout@v2

         - name: Use Node.js
           uses: actions/setup-node@v2
           with:
              node-version: "20.x"
              cache: "yarn"

         - name: Install Dependencies
           run: yarn install

         - name: Run Prettier
           run: npx prettier --check .
